server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/zerith}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:zerith}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:zerith}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

mqtt.enabled=${MQTT_ENABLED:true}
mqtt.broker.url=${MQTT_BROKER_URL:tcp://localhost:1883}
mqtt.client.id=${MQTT_CLIENT_ID:zerith-backend}
