spring.datasource.url=jdbc:postgresql://localhost:5432/zerith
spring.datasource.username=zerith
spring.datasource.password=zerith
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

mqtt.enabled=true
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=zerith-backend
